# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ian Oxborrow
title: Junior Software Engineer
email: ian.s.oxborrow@gmail.com
website: oxborrow.co

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  IanOxborrow
stackoverflow_username: "3789915"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ian-oxborrow-541a231a9
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi I'm Ian. I am an honours student with a passion for machine learning and experience in mobile app development.
  
  I am most skilled in: <mark>Android</mark> and <mark>React Native</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Facial Landmark-Based Morphing using Thin Plate Spline Interpolation
        link: https://github.com/IanOxborrow/the-emojification-of-will-greyham
        link_text: The Emojification of Will Greyham
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This project was an experiment in using machine learning techinques in conjunction with mathematical techinques to morphed a face to match a target. Through the identification of facial landamarks, a thin plate spline is generated, allowing for smooth transitions between two images.
      - layout: top-middle
        title: Sensible
        link: https://play.google.com/store/apps/details?id=au.com.erigma.sensible
        link_text: Sensible on Google Play
        description: |
          Developed a cross platform data collection app using React Native. As part of the project, I had to collaborate as a technology lead within a small team of six. During this period, I also familiarised and trained new developers with the codebase and technology stack.   
      - layout: top-middle
        title: Developed server running Flux and Kubernetes
        link: 
        link_text: <>
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This project was started as a way of teaching myself how to use Kubernetes. Since then, the cluster now manages most of my servers. In its current state the cluster is running Prometheus, Grafana, Plex, Tautulli, Jellyfin, Terraria and Minecraft with plans to introduce a nextcloud instance and a jupyterhub instance.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Origma Pty Ltd
        sub_title: Python Developer
        caption: August 2023 - December 2023
        description: |
          During my time at Origma, I was assigned to work on various open source project that would contribute in a positive way to the community. I chose to work on an automated moderation bot for a Reddit-like platform called Lemmy. This project gave me the opportunity to apply the machine learning knowledge I had gained at ANU in a practical context, while also giving me experience in updating an application with existing releases and an existing userbase.
      - layout: left
        title: Stripy Sock
        sub_title: Junior Developer
        caption: April 2023 - August 2023
        description: | # this will include new lines to allow paragraphs
            I was a junior Android developer for TapApp, a app for offenders developed in collaboration with the New South Wales government. As a developer, part of by job was self directed developmet of features that involved in-depth knowledge of techonolgies such as Jetpack Compose and best practice Android app architecture.
      - layout: left
        title: Big W
        link: https://www.bigw.com.au
        link_text: bigw.com.au
        sub_title: Fill Team
        caption: November 2017 - Present
        description: | # this will include new lines to allow paragraphs
            My role in Big W was as a fill team member. This role had me working in small teams of two to six and had me interfacing directly with customers. Durning this period I learned to effectivly work within an orginastional structure with a customer facing focus, as wall as leading small teams.
      - layout: left
        title: BiPi Pty Ltd
        sub_title: Lead Developer
        caption: January 2020 - November 2020
        description: | # this will include new lines to allow paragraphs
            I undertook my role at BuildItPayIt as part of ANU's TechLauncher program. Under this program, students complete an internship, gaining experience in a professional work environment and with a real project. As a part of the team, I was responsible for building a mobile application that allows builders to collect payment and hold it in esgrow.

            My role included developing the app's front-end using React Native, and integrating RESTful APIs with the backend to retrieve and display data. Part of my responsibility included designing the bulk of the UX/UI of the app. The team and I were also involved with directly engaging stakeholders to ensure their needs and requirements were being met throughout the project. This involved regular communication, presenting progress updates, and gathering feedback to make necessary adjustments.

            Throughout my time at BiPi, I learned a lot about React Native, especially its capabilities for cross-platform mobile application development. I also gained experience in Agile methodologies, including Scrum and Kanban, which helped our team work together more efficiently and effectively.

            Overall, my experience as a React Native developer at BiPi was extremely fulfilling, and I am proud of the work that the team and I accomplished. The skills and knowledge that I gained during my time there have been invaluable, and I look forward to using them in future projects.
    
              
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Australian National University
        caption: 2018 - 2023
        sub_title: B Software Engineering (Honours)
        description: | # this will include new lines to allow paragraphs
          * Major: Advanced Intelligent Systems
          * Minor: Computer Science Foundations

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
